python3 main_continual.py \
    --dataset cifar100 \
    --encoder resnet18 \
    --data_dir $DATA_DIR \
    --seed $SEED \
    --split_strategy class \
    --max_epochs 500 \
    --num_tasks $NUM_TASKS \
    --task_idx 1 \
    --gpus 0 \
    --num_workers 4 \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --scheduler warmup_cosine \
    --lr 0.6 \
    --classifier_lr 0.3 \
    --weight_decay 1e-4 \
    --batch_size 256 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --gaussian_prob 0.0 0.0 \
    --solarization_prob 0.0 0.2 \
    --name $NAME \
    --wandb \
    --project cifar100 \
    --entity sungmin-cha \
    --save_checkpoint \
    --method mocov2plus \
    --distiller mocov2plus_pnr \
    --proj_hidden_dim 2048 \
    --queue_size 65536 \
    --temperature 0.2 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 0.999 \
    --momentum_classifier \
    --distill_temperature 0.2 \
    --pretrained_model $PRETRAINED_PATH


